language: node_js
node_js:
  - 18
branches:
  only:
    - master
cache:
  npm: true
script:
  - git config --global user.name "${GH_NAME}"
  - git config --global user.email "${GH_EMAIL}"
  - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
  - npm install
  - GIT_USER="${GH_NAME}" npm deploy